# Generated by Django 3.0.8 on 2021-11-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20211108_2338'),
        ('help_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='helpmessage',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='helpmessage',
            name='surname',
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer'),
        ),
    ]
