# Generated by Django 3.0.8 on 2021-11-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20211108_2338'),
        ('help_chat', '0002_auto_20211129_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmessage',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer'),
        ),
        migrations.AlterField(
            model_name='helpmessage',
            name='message',
            field=models.TextField(unique=True, verbose_name='Описание проблемы'),
        ),
    ]
