# Generated by Django 3.0.8 on 2021-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_chat', '0003_auto_20211130_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpmessage',
            name='customer',
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='email',
            field=models.EmailField(default='test@mail.ru', max_length=100, verbose_name='Элетронная почта'),
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='firstname',
            field=models.CharField(default='Not provided', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='surname',
            field=models.CharField(blank=True, default='Not provided', max_length=50, verbose_name='Фамилия'),
        ),
    ]
