version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-shop
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/config:/etc/nginx/conf.d/
    depends_on:
      - web


  web:
    build: .
    container_name: django-backend
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ENGINE=${DB_ENGINE}
    ports:
      - "8000:8000"

