# Generated by Django 3.0.8 on 2021-12-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20211108_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='Цена')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
